#! /usr/bin/env python3.5
import re

def main():
    bannedCards = [
    "Intangible Virtue (Innistrad-Avacyn Restored block)"
    ,"Lingering Souls (Innistrad-Avacyn Restored block)"
    ,"AEther Vial (Mirrodin block)"
    ,"Ancient Den (Mirrodin block)"
    ,"Arcbound Ravager (Mirrodin block)"
    ,"Darksteel Citadel (Mirrodin block)"
    ,"Disciple of the Vault (Mirrodin block)"
    ,"Great Furnace (Mirrodin block)"
    ,"Seat of the Synod (Mirrodin block)"
    ,"Tree of Tales (Mirrodin block)"
    ,"Vault of Whispers (Mirrodin block)"
    ,"Skullclamp (Mirrodin block)"
    ,"Lin Sivvi, Defiant Hero (Masques block)"
    ,"Rishadan Port (Masques block)"
    ,"Gaeas Cradle (Urza block)"
    ,"Memory Jar (Urza block)"
    ,"Serras Sanctum (Urza block)"
    ,"Time Spiral (Urza block)"
    ,"Tolarian Academy (Urza block)"
    ,"Voltaic Key (Urza block)"
    ,"Windfall (Urza block)"
    ,"Cursed Scroll (Tempest block)"
    ,"Squandered Resources (Mirage block)"
    ,"Amulet of Quoz (Ice Age Block)"
    ,"Thawing Glaciers (Ice Age block)"
    ,"Zuran Orb (Ice Age block)"
    ,"Ancient Den"
    ,"Birthing Pod"
    ,"Blazing Shoal"
    ,"Bloodbraid Elf"
    ,"Chrome Mox"
    ,"Cloudpost"
    ,"Dark Depths"
    ,"Deathrite Shaman"
    ,"Dig Through Time"
    ,"Dread Return"
    ,"Eye of Ugin"
    ,"Glimpse of Nature"
    ,"Great Furnace"
    ,"Green Suns Zenith"
    ,"Hypergenesis"
    ,"Jace, the Mind Sculptor"
    ,"Mental Misstep"
    ,"Ponder"
    ,"Preordain"
    ,"Punishing Fire"
    ,"Rite of Flame"
    ,"Seat of the Synod"
    ,"Second Sunrise"
    ,"Seething Song"
    ,"Senseis Divining Top"
    ,"Skullclamp"
    ,"Splinter Twin"
    ,"Stoneforge Mystic"
    ,"Summer Bloom"
    ,"Treasure Cruise"
    ,"Tree of Tales"
    ,"Umezawas Jitte"
    ,"Vault of Whispers"
    ,"Ancestral Recall"
    ,"Balance"
    ,"Black Lotus"
    ,"Brainstorm"
    ,"Chalice of the Void"
    ,"Channel"
    ,"Demonic Consultation"
    ,"Demonic Tutor"
    ,"Dig Through Time"
    ,"Fastbond"
    ,"Flash"
    ,"Imperial Seal"
    ,"Library of Alexandria"
    ,"Lions Eye Diamond"
    ,"Lodestone Golem"
    ,"Lotus Petal"
    ,"Mana Crypt"
    ,"Mana Vault"
    ,"Memory Jar"
    ,"Merchant Scroll"
    ,"Minds Desire"
    ,"Mox Emerald"
    ,"Mox Jet"
    ,"Mox Pearl"
    ,"Mox Ruby"
    ,"Mox Sapphire"
    ,"Mystical Tutor"
    ,"Necropotence"
    ,"Ponder"
    ,"Sol Ring"
    ,"Strip Mine"
    ,"Time Vault"
    ,"Time Walk"
    ,"Timetwister"
    ,"Tinker"
    ,"Tolarian Academy"
    ,"Treasure Cruise"
    ,"Trinisphere"
    ,"Vampiric Tutor"
    ,"Wheel of Fortune"
    ,"Windfall"
    ,"Yawgmoths Bargain"
    ,"Yawgmoths Will"
    ,"Advantageous Proclamation"
    ,"Amulet of Quoz"
    ,"Ancestral Recall"
    ,"Backup Plan"
    ,"Balance"
    ,"Bazaar of Baghdad"
    ,"Black Lotus"
    ,"Bragos Favor"
    ,"Bronze Tablet"
    ,"Channel"
    ,"Chaos Orb"
    ,"Contract from Below"
    ,"Darkpact"
    ,"Demonic Attorney"
    ,"Demonic Consultation"
    ,"Demonic Tutor"
    ,"Dig Through Time"
    ,"Double Stroke"
    ,"Earthcraft"
    ,"Falling Star"
    ,"Fastbond"
    ,"Flash"
    ,"Frantic Search"
    ,"Goblin Recruiter"
    ,"Gush"
    ,"Hermit Druid"
    ,"Immediate Action"
    ,"Imperial Seal"
    ,"Iterative Analysis"
    ,"Jeweled Bird"
    ,"Library of Alexandria"
    ,"Mana Crypt"
    ,"Mana Drain"
    ,"Mana Vault"
    ,"Memory Jar"
    ,"Mental Misstep"
    ,"Mind Twist"
    ,"Minds Desire"
    ,"Mishras Workshop"
    ,"Mox Emerald"
    ,"Mox Jet"
    ,"Mox Pearl"
    ,"Mox Ruby"
    ,"Mox Sapphire"
    ,"Muzzios Preparations"
    ,"Mystical Tutor"
    ,"Necropotence"
    ,"Oath of Druids"
    ,"Power Play"
    ,"Rebirth"
    ,"Secret Summoning"
    ,"Secrets of Paradise"
    ,"Sentinel Dispatch"
    ,"Shahrazad"
    ,"Skullclamp"
    ,"Sol Ring"
    ,"Strip Mine"
    ,"Survival of the Fittest"
    ,"Tempest Efreet"
    ,"Time Vault"
    ,"Time Walk"
    ,"Timetwister"
    ,"Timmerian Fiends"
    ,"Tinker"
    ,"Tolarian Academy"
    ,"Treasure Cruise"
    ,"Unexpected Potential"
    ,"Vampiric Tutor"
    ,"Wheel of Fortune"
    ,"Windfall"
    ,"Worldknit"
    ,"Yawgmoths Bargain"
    ,"Yawgmoths Will"
    ]
    for idx, card in enumerate(bannedCards):
        if "(" in card:
            parenLocation = card.find("(")
            bannedCards[idx] = card[0:(parenLocation - 1)]
    
    f = open("listOneWord.txt","r")

    lines = f.readlines()

    for bannedCard in bannedCards:
        if bannedCard in lines:
            print (bannedCard)
            lines.remove(bannedCard)
    f.close()
    p = open("listFinal.txt", "w")
    for line in lines:
        p.write(line)

    p.close()
if __name__ == "__main__":
    main()
